teleop_twist_joy_node:
  ros__parameters:
    enable_button: 0             # A button
    require_enable_button: true

    axis_linear: 1               # Left stick Y (forward/back)
    scale_linear: -1.5           # Negative to make UP = +0.2

    axis_angular: 3              # Right stick X (rotation)
    scale_angular: -2.0          # Clockwise should be positive z

    scale_linear_turbo: 2.5
    scale_angular_turbo: 4.0
